### ISSUE TITLE
Definir o nome do sistema

### ISSUE THREAD

**Issue by gustavocamalionti** [gustavocamalionti/timecosmic#5]
Como discutido na issues https://github.com/gustavocamalionti/cosmichub/issues/4 que definimos o objetivo do projeto, um nome legal e que não existe nenhuma referência dele (pelo menos nas primeiras consultas do google) seria:

[www.cosmichub.com.br](http://www.cosmichub.com.br/)

Apesar de simples e lógico, chegar em um nome que transmite a ideia de um HUB de comunicação, onde acontecerá interações entre usuários e ainda servir como um portal de notícias do mundo ciêntifico foi beeem demorado haahahah

**Comment by gustavocamalionti** [comment]
Como discutido na issues #4 que **definimos o objetivo do projeto**, um nome super legal e que não existe nenhuma referência dele (pelo menos nas primeiras consultas do google) seria:

www.cosmichub.com.br

Apesar de simples e lógico, chegar em um nome que transmite a ideia de um HUB de comunicação, onde acontecerá interações entre usuários e ainda servir como um portal de notícias do mundo ciêntifico foi beeem demorado haahahah

**Comment by gustavocamalionti** [comment]
Após voltar a pesquisar se existe algum domínio chamado cosmichub, tive a grande surpresa que já estava sendo usado para venda o www.cosmichub.com, não sei se eu deveria pensar em outro ou comprar o ".com.br" no registro.br mesmo

**Comment by gustavocamalionti** [comment]
Depois de procurar bastante e tentar relacionar ciência com forum e feed, cheguei ao seguinte domínio:

`www.timecosmic.com.br.`

Basicamente, o nome em si não remete tanto a um ambiente de troca de conhecimento entre os usuários, que é uma das ideias principais. No entanto, ele faz referência a ciência e ao cosmos, logo, no primeiro contato é de se esperar que a aplicação explique melhor como as coisas funcionam.

O **Time** no domínio teria a ideia de
 
```
"dedicar um tempo para o cosmos, ou, a ciência em si".
```

Eu gostei bastante da escolha, principalmente por ser um domínio pequeno, facil de compreender e lembrar. Além de que, não há nenhum `timecosmic` existente.

**Comment by AnthonyOliveira5** [comment]
Meu, que domínio maneiro, mal posso esperar pra ver o andamento!
